
.PHONY: build node_modules

all: node_modules lint test

node_modules:
	@echo "+ $@"
	@npm install

lint:
	@echo "+ $@"
	@npm run lint

build:
	@echo "+ $@"
	@npm run build

test:
	@echo "+ $@"
	@npm run test
