dist: xenial
sudo: "required"

language: "go"

go:
    - 1.12.7

env:
  global:
    - GO111MODULE=on
    - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
  matrix:
    - BUILD_TYPE=Backend
    - BUILD_TYPE=Frontend

services:
    - "docker"

before_install:
  - sudo apt-get update

script:
    - |
      case "${BUILD_TYPE}" in
        Backend)
          make backend
          ;;
        Frontend)
          make frontend
          ;;
        *)
          echo "Unknown BUILD_TYPE value"
          exit 1
      esac
